- .travis.yml
- core/src/main/java/org/fao/geonet/geocat/kernel/UnpublishInvalidMetadataJob.java
- core/src/main/java/org/fao/geonet/kernel/SchematronValidator.java
Tests: 
Note: this has already been deployed on dev. Not to be merged until geocat tested and gave it a go.
> Sb366 - Schematron BGDI issue

- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
Same as the previous ones ... Tested locally & already applied by hand on dev.
> editor - number of dimensions non multilingual (SB-384)

- web-ui/src/main/resources/catalog/geocat-shared-objects/js/extent-directive.js
> Allow to fill extent outside Swiss projection extent

- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/eng/schematron-rules-geonetwork.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/schematron/schematron-rules-geonetwork.sch
- schemas/iso19139.che/src/main/plugin/iso19139.che/update-fixed-info.xsl
Add schematron to detect empty translations
> Remove empty translations on save and indexation

- web-ui/src/main/resources/catalog/views/geocat/templates/top-bar.html
Link to news, documentation and about pages use http
> Restore http link to external pages

- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
The elements having a fieldset added:
* che:CHE_MD_Association
* che:CHE_MD_AbstractClass
* che:CHE_MD_Class
> Add a fieldset around class stuff  when editing

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- schemas/iso19139.che/src/main/plugin/iso19139.che/schematron/schematron-rules-url-check.report_only.sch
Fixed as well the validation of the MD when we updated it. It was not doing
it even when asked to.
> Fix URL validation

- web-ui/src/main/resources/catalog/views/geocat/templates/top-bar.html
- web/src/main/webapp/xsl/banner.xsl
- web/src/main/webapp/xsl/geocat_widgetui.xsl
See https://jira.swisstopo.ch/browse/GEOCAT_SB-488 for details.
> Point to the new CMS

- schemas/iso19139.che/pom.xml
- schemas/iso19139.che/src/main/java/org/fao/geonet/api/gm03/Gm03Api.java
- schemas/iso19139.che/src/main/java/org/fao/geonet/api/gm03/ISO19139CHEtoGM03.java
- schemas/iso19139.che/src/main/java/org/fao/geonet/api/gm03/ISO19139CHEtoGM03Base.java
- schemas/iso19139.che/src/main/java/org/fao/geonet/api/gm03/ISO19139CHEtoGM03small.java
- schemas/iso19139.che/src/main/java/org/fao/geonet/api/gm03/UnDuplifier.java
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/19139CHE-to-GM03.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/content.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/data-quality.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/distribution.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/extent.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/header.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/identification.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/legislation.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/maintenance-info.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/metadata.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/ref-system.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/resp-party.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/convert/19139CHEtoGM03/spatial_repr.xsl
Add GM03 support.
Related to https://jira.swisstopo.ch/browse/MGEO_SB-9
- Spring service  `srv/api/records/2230394a-0124-4b74-83a7-e8a161b8b5f3/formatters/gm03`
- GM03 Converter classes (from geocat).
Todo:
> GM03 / Add spring service for convertion

- Jenkinsfile
Change Jenkins build maven options to use Postgis instead of shapefile for spatial index.
> Use postgis spatial index

- s3sync-geocat-folders.sh
- web/pom.xml
- web/src/docker/Dockerfile
- web/src/docker/docker-entrypoint.d/00-configure-s3
- web/src/docker/docker-entrypoint.d/credentials
- web/src/docker/docker-entrypoint.sh
and dedicated entrypoint to install s3 credentials
> Add s3 sync script

- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataJob.java
- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataJobService.java
- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataReport.java
- core/src/main/java/org/fao/geonet/util/XslUtil.java
- core/src/main/resources/config-spring-geonetwork.xml
- domain/src/main/java/org/fao/geonet/domain/geocat/PublishRecord.java
- domain/src/main/java/org/fao/geonet/repository/geocat/PublishRecordRepository.java
- domain/src/main/java/org/fao/geonet/repository/geocat/specification/PublishRecordSpecs.java
- domain/src/test/java/org/fao/geonet/repository/geocat/specification/PublishRecordSpecsTest.java
- services/src/main/java/org/fao/geonet/api/records/backup/BackupArchiveApi.java
- web/src/main/webapp/WEB-INF/classes/log4j.xml
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
- web/src/main/webapp/WEB-INF/config.xml
- web/src/main/webapp/WEB-INF/data/data/formatter/bs_simple/config.properties
- web/src/main/webapp/WEB-INF/data/data/formatter/bs_simple/loc/README
- web/src/main/webapp/WEB-INF/data/data/formatter/bs_simple/view.xsl
- web/src/main/webapp/xslt/geocat/unpublish-report-html.xsl
- web/src/main/webapp/xslt/geocat/unpublish-report.xsl
Get unpublish tasks, services, reports and jobs from old geocat.
Exports look quite good but can't manage to execute the unpublishMetadata Quartz !!!
The one from archive backup is working fine but can't fix it for unpublishMetadata ...
Please @cmangeat and @fxprunayre can have a look on sprint quartz ScheduleManager and CRON definitions, and look why UnpublishMetadataJob service can't launch it ?
Maybe i missed something.
I've tested to launch it from spring service, and put the Job in same package as backup archive but still the same.
Thanks
> Backport unpublish metadata CRON Job and Reports

- schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/SummaryFactory.groovy
- services/src/main/java/org/fao/geonet/api/records/MetadataUtils.java
- services/src/main/java/org/fao/geonet/api/records/model/related/AssociatedSiblingMetadataItem.java
- services/src/main/java/org/fao/geonet/api/records/model/related/RelatedResponse.java
- web-ui/src/main/resources/catalog/js/GnFormatterLib.js
- web/src/main/webapp/WEB-INF/data/data/formatter/groovy/common/Handlers.groovy
- web/src/main/webapp/WEB-INF/data/data/formatter/html/associated.html
- web/src/main/webapp/xslt/services/metadata/relation.xsl
fix siblings
fix associations
fix nesting
Like before in https://www.geocat.ch/geonetwork/srv/fre/catalog.search#/metadata/856bf4eb-d605-44fc-ae6e-cb54e011ae64
> Formatter: fix nested hierarchy view

- web-ui/src/main/resources/catalog/components/catalog/CatalogService.js
> Md view: properly merge keywordGroup if it is an array

- schemas/iso19139.che/src/main/plugin/iso19139.che/process/migration3_4.xsl
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-241
> XSL migration / Fix expiry date check.

- web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js
- web-ui/src/main/resources/catalog/js/GeocatGnFormatterViewerModule.js
- web-ui/src/main/resources/catalog/views/geocat/less/gn_formatter_viewer_geocat.less
- web-ui/src/main/resources/catalog/views/geocat/less/gn_formatter_viewer_geocat_geocat.less
- web-ui/src/main/resources/catalog/views/geocat/templates/home.html
- web-ui/src/main/resources/catalog/views/geocat/templates/list.html
- web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml
- web/src/main/webapp/WEB-INF/config.xml
- web/src/main/webapp/xslt/base-layout.xsl
- web/src/main/webapp/xslt/common/base-variables.xsl
http://localhost:8080/geonetwork/srv/eng/md.viewer?debug#/full_view/d8f57631-e877-4f5b-b982-589fdd82471c
> Add back md.viewer service for backward compatibility

- Jenkinsfile
- web/src/docker/Dockerfile
- web/src/docker/enable_gzip.augtool
now, failure on docker image build or push will trigger an error on jenkins
> Enable gzip compression and allow failure only when building webapp

- web-ui/src/main/resources/catalog/components/search/searchmanager/SearchFormDirective.js
- web-ui/src/main/resources/catalog/views/geocat/templates/index.html
> wait for pagination directive to be registred before to laucnh search

- core/src/main/java/org/fao/geonet/kernel/DataManager.java
- core/src/main/java/org/fao/geonet/kernel/setting/SettingManager.java
- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataJob.java
See https://jira.swisstopo.ch/browse/MGEO_SB-309
> Unpublish job: when incoherent validation status between index and DB, trigger indexation

- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataJob.java
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
See https://jira.swisstopo.ch/browse/MGEO_SB-309
Previously record was only re-indexed if it was altered (i.e. unpublished)
> MGEO_SB-309 unpublishing job now always indexes records

- web-ui/src/main/resources/catalog/views/geocat/directives/instancelabel.js
- web-ui/src/main/resources/catalog/views/geocat/directives/partials/instancelabel.html
- web-ui/src/main/resources/catalog/views/geocat/less/gn_search_geocat.less
- web-ui/src/main/resources/catalog/views/geocat/module.js
- web-ui/src/main/resources/catalog/views/geocat/templates/index.html
Issue: https://jira.swisstopo.ch/browse/MGEO_SB-351
Label appears when either "[dev]" or "[int]" is present in the instance name.
> Adds DEV and INT instance labels to public page

- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/layout.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/schema/gmd/identification.xsd
- schemas/iso19139.che/src/main/plugin/iso19139.che/update-fixed-info.xsl
> Extra topics for military intelligence

- schemas/iso19139.che/src/main/java/org/fao/geonet/schema/iso19139che/ISO19139cheSchemaPlugin.java
- schemas/iso19139.che/src/main/plugin/iso19139.che/update-fixed-info.xsl
- schemas/iso19139/src/main/java/org/fao/geonet/schema/iso19139/ISO19139SchemaPlugin.java
- schemas/iso19139/src/main/plugin/iso19139/process/empty.xsl
- schemas/iso19139/src/main/plugin/iso19139/templates/vector-multilingual.xml
- schemas/iso19139/src/main/plugin/iso19139/update-fixed-info.xsl
Combine 
* https://github.com/geonetwork/core-geonetwork/pull/3533
* https://github.com/geonetwork/core-geonetwork/pull/3556
* + changes for iso19139.che
* includes also basic support of Anchor (related to https://github.com/geonetwork/core-geonetwork/pull/3078)
> Multilingual ordering

- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl
- web-ui/src/main/resources/catalog/views/default/templates/recordView.html
https://jira.swisstopo.ch/browse/MGEO_SB-455
> Fix for 455

- services/src/main/java/org/fao/geonet/api/links/LinksApi.java
- web-ui/src/main/resources/catalog/js/admin/DashboardRecordLinkController.js
- web-ui/src/main/resources/catalog/templates/admin/dashboard/record-links.html
* Add super basic paging to see more links
* Add link to record on ID
> Link Checker / Basic paging.

- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-474
> Angular view / Display link title when protocol is download.

- schemas/iso19139.che/src/main/plugin/iso19139.che/schema-suggestions.xml
There is no restriction of 8 attributes.
Fix for 442
> Feature catalogue / Add description when adding attribute in simple view

- core/src/main/java/org/fao/geonet/constants/Geonet.java
- core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataIndexer.java
- es/es-dashboards/geocatch-indicators.md
- web-ui/src/main/resources/catalog/locales/en-core.json
- web-ui/src/main/resources/catalog/templates/editor/directory.html
- web/src/main/webapp/WEB-INF/config-lucene.xml
- web/src/main/webapp/WEB-INF/config-summary.xml
https://jira.swisstopo.ch/browse/MGEO_SB-485
> Facet / Add owner name

- es/es-dashboards/geocatch-indicators.md
- web-ui/src/main/resources/catalog/components/common/needhelp/NeedHelpDirective.js
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/en-core.json
and fallback to english version if translation not available.
> Documentation / Fix link

- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/views/default/templates/searchForm.html
- web-ui/src/main/resources/catalog/views/geocat/less/gn_search_geocat.less
- web-ui/src/main/resources/catalog/views/geocat/module.js
- web-ui/src/main/resources/catalog/views/geocat/templates/index.html
- web-ui/src/main/resources/catalog/views/geocat/templates/results.html
- web-ui/src/main/resources/catalog/views/geocat/templates/searchForm.html
* User (reviewer or more) can save a search
* Admin can make a search public (ie. featured)
* Search can also be shared only by member of a group
* Public saved search are displayed next to the main input search box
* Do not display geocat header if not in main portal - ie. avoid geocat
logo when a sub portal is created.
> Search / Add saved search panel

- web-ui/src/main/resources/catalog/components/usersearches/partials/featuredusersearchesbutton.html
- web-ui/src/main/resources/catalog/views/geocat/less/gn_search_geocat.less
- web-ui/src/main/resources/catalog/views/geocat/templates/searchForm.html
> User search / CSS improvements.

- services/src/main/java/org/fao/geonet/api/ApiUtils.java
Introduced in 204d2bccd12afc3331b7267f6741c472bc2e0d9d
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-545
> Owner change / Record not found

- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/default.xsl
- web-ui/src/main/resources/catalog/components/common/map/externalviewer.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/js/CatController.js
- web-ui/src/main/resources/catalog/locales/de-search.json
- web-ui/src/main/resources/catalog/locales/en-search.json
- web-ui/src/main/resources/catalog/locales/fr-search.json
- web-ui/src/main/resources/catalog/locales/it-search.json
- web-ui/src/main/resources/catalog/views/default/templates/recordViewGeocat.html
Same as https://github.com/geoadmin/geocat/pull/187 but for the new main branch
> Map improvements

- core/src/main/java/org/fao/geonet/kernel/unpublish/UnpublishInvalidMetadataReport.java
- services/src/main/java/org/fao/geonet/api/ApiUtils.java
- web/src/main/webapp/xslt/geocat/xml_iso19139.xsl
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-547
Cosmetic change for CSW response
> Admin / Geocat / Fix NPE. Not sure about the root cause

- schemas/iso19139.che/src/main/java/org/fao/geonet/schema/iso19139che/ISO19139cheSchemaPlugin.java
- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/default.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
- schemas/iso19139.che/src/main/resources/config-spring-geonetwork.xml
- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf
- web/src/main/webapp/xslt/ui-metadata/form-builder.xsl
+ merge to master.
https://jira.swisstopo.ch/browse/MGEO_SB-490 is disabled for now. Waiting for the thesaurus to be completed by swisstopo before activating it.
> ISO19139.che / Editor / Use thesaurus for other constraints.

- schemas/iso19139.che/src/main/plugin/iso19139.che/update-fixed-info.xsl
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-549
> ISO19139.che / Force language to be encoded with Language code instead of characterString.

- web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
Cf. https://jira.swisstopo.ch/browse/MGEO_SB-550
> Record view / Hide RDF export

- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf
https://jira.swisstopo.ch/browse/MGEO_SB-490
> Thesaurus / Update access and use 

- schemas/iso19139/src/main/plugin/iso19139/loc/fre/labels.xml
https://jira.swisstopo.ch/browse/MGEO_SB-621
> Editor / French / Use limitation / Remove helper list.

- web-ui/src/main/resources/catalog/js/admin/UserGroupController.js
Fix https://jira.swisstopo.ch/browse/MGEO_SB-635
Related to https://github.com/geoadmin/geocat/commit/766e544c65ddba0a9be11ca6219d1666caf3f243
Solved by aligning with GeoNetwork.
> Admin / User admin / can see all groups.

- schemas/iso19139.che/src/main/plugin/iso19139.che/process/copy-contact-to-pointofcontact.xsl
Fix for https://jira.swisstopo.ch/browse/MGEO_SB-640
Can be tested with
```
curl -X GET "http://localhost:8080/geonetwork/srv/api/0.1/processes/copy-contact-to-pointofcontact?uuids=a60bca37-aeaf-47f4-acd7-edd90f568c8e&appendFirst=false" -H "accept: */*" -H "X-XSRF-TOKEN: 880727f0-633e-4799-8b78-81846d139952"
```
> ISO19139.che / Process / Copy citedResponsibleParty as pointOfContact.

- harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/AbstractParams.java
Same approach to unset the value on update for CSW. See https://github.com/geonetwork/core-geonetwork/blob/master/harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/csw/CswParams.java#L119.
> Harvester / From folder / Unable to reset XSLT once set

- web-ui/src/main/resources/catalog/templates/editor/new-metadata-horizontal.html
Related to https://jira.swisstopo.ch/browse/MGEO_SB-580
> New metadata / No empty group.

- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
- web-ui/src/main/resources/catalog/locales/de-search.json
See https://jira.swisstopo.ch/browse/MGEO_SB-621
> ISO19139.che / Do not display access use conditions thesaurus in thesaurus picker

- web/src/main/webapp/WEB-INF/data/config/codelist/external/thesauri/theme/access_use_conditions.rdf
See https://jira.swisstopo.ch/browse/MGEO_SB-621
> Terms of use / Add Italian prefix for Opendata

- schemas/iso19139.che/src/main/plugin/iso19139.che/config/associated-panel/default.json
- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/default.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/layout/utility-tpl.xsl
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/eng/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/fre/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/ger/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/ita/labels.xml
- schemas/iso19139/src/main/plugin/iso19139/layout/utility-tpl.xsl
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js
- web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedDirective.js
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/components/metadatamanager/EditorService.js
- web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js
- web-ui/src/main/resources/catalog/components/search/formfields/partials/schemainfocombo.html
- web-ui/src/main/resources/catalog/locales/de-geocat.json
- web-ui/src/main/resources/catalog/locales/en-geocat.json
- web-ui/src/main/resources/catalog/locales/fr-geocat.json
- web-ui/src/main/resources/catalog/locales/it-geocat.json
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
- web/src/main/webapp/WEB-INF/classes/setup/sql-geocat/maintenance-629.sql
- web/src/main/webapp/xslt/ui-metadata/edit/edit.xsl
Backport of https://github.com/geonetwork/core-geonetwork/pull/5465
* SQL script to simplify list of possible values
* GEOSHOP URL display all formats of the record
* Avoid to loose protocol when a value is not in the list
* Add ESRI:REST and MAP:Preview protocol
Relates to https://jira.swisstopo.ch/browse/MGEO_SB-629
> Editor / List formats as protocols. 

- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/eng/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/fre/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/ger/labels.xml
- schemas/iso19139.che/src/main/plugin/iso19139.che/loc/ita/labels.xml
- web-ui/src/main/resources/catalog/components/edit/editorhelper/EditorHelperDirective.js
- web-ui/src/main/resources/catalog/components/edit/editorhelper/partials/editorhelper.html
- web-ui/src/main/resources/catalog/components/metadataactions/RelatedResourcesService.js
- web-ui/src/main/resources/catalog/components/metadataactions/partials/related.html
- web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less
Backport of https://github.com/geonetwork/core-geonetwork/pull/5644
+ protocol for shops
> Editor / List format as protocol in helper list 

- services/src/main/java/org/fao/geonet/api/registries/DirectoryApi.java
- services/src/main/java/org/fao/geonet/api/registries/DirectoryUtils.java
- web/src/main/webapp/WEB-INF/classes/setup/sql-geocat/jira-MGEO_SB-650/README.md
https://jira.swisstopo.ch/browse/MGEO_SB-650
> geocat.ch / Update extent
