geoadmin/geocat

schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
Do not add a multilingual block for gmd:geometricObjectCount (Fixing #SB-384)
Before:
After:
Tests: runtime tested.
=> multilingual field on editing for geometric object count

schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
Need to exclude the `<gmd:attributeDescription>` and its descendant `<gco:RecordType>` from the multilingual fields. This to address the second part of the ticket SB-384 (see https://jira.swisstopo.ch/browse/GEOCAT_SB-384)
Tests: at runtime:
=> exclude attributeDescription from multilingual fields (SB-384)

core/src/main/java/org/fao/geonet/kernel/EditLib.java, core/src/main/java/org/fao/geonet/kernel/SchemaSuggestions.java, schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml, schemas/iso19139.che/src/main/plugin/iso19139.che/schema-suggestions.xml
It was creating a gmd:CI_ResponsibleParty directly under the gmd:distributor.
Added a filter capability in the schema-suggestion.xml file to not create the
gmd:distributorContact, but to let the user create it using sharedObjects.
=> SB-393: Fixed gmd:distributor creation

schemas/iso19139.che/src/main/plugin/iso19139.che/layout/layout.xsl
In edit mode, the current XSL form:
```xsl
<xsl:select="if (boolean) ...">
```
does not seem to work. It needs to be explicitely compared to true, or this leads to the following error in GN when XSL-transforming:
"An empty sequence is not allowed as the value of parameter $name"
Tests:
- utests: testsuite (on schemas/) OK
- runtime tested on both reported MD (service md.edit): OK.
=> swiss profile - fixing transformation (sb-423)

services/src/main/java/org/fao/geonet/services/metadata/AjaxEditUtils.java
Right now, when we add a sub topic category, it also adds its parent (done in update fixed info).
If you add 2 sub topic categories from the same parent, the parent is added just once in the medatadata.
The issue is that all subcategories that doesn't have its parent as direct preceding sibling are removed from metadata. So it could just keep one subcategory from same parent.
Removing the geocat specific stuff in `applyChangesEmbedded` for topic categories fixes the issue.
I'm not really sure why, because the code that i removed just detach the main category if a sub one is present ...
That's why i would appreciate a review. @pvalsecc ?
=> editor: Don't detach topiCategory parent when adding a children

services/src/main/java/org/fao/geonet/services/metadata/Publish.java
If publishing, a test on the setOperation was made, returning false if the operation could not be added to the operationallowed (which occurs if the operation is already set in the db).
Returning false leads to missing operations in the table, making it impossible to actually publish a md, even if the user has the right to publish it.
IMHO the behaviour has to be coherent between publish and unpublish.
Tests:
* runtime, using same db state for the tested md (id: 2001525)
* testsuite on the whole services module is broken, and somehow hangs in
maven.
* PublishTest.java suite is OK
Note:
This patch could be backported to gn upstream, if relevant.
=> Fixing publish / unpublish logic (SB-434)

core/src/main/java/org/fao/geonet/kernel/search/index/IndexingTask.java, core/src/main/java/org/fao/geonet/util/XslUtil.java
When tomcat was restarted and the first MD was viewed by a user, the
MD was re-indexed (to update the view counter) in a Quartz thread.
This Quartz thread never had his ServiceContext initialized and that
made the ISO3 to ISO2 conversion unable to convert the codes.
I guess something later on is setting the ServiceContext for the Quartz
thread and the problem doesn't happen anymore, because only the first MD
that is viewed is corrupted.
=> Fix MD language corruption

schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml
This allows the block for che:attribute to be deletable, see:
https://jira.swisstopo.ch/browse/GEOCAT_SB-433
Tests:
- runtime
- utests on schemas/ ok
=> iso19139.che - che:attribute as fieldsWithFieldset

web/src/main/webapp/xslt/common/functions-metadata.xsl, web/src/main/webapp/xslt/ui-metadata/form-configurator.xsl
When configuring a field in one of the views of the config-editor.xml
file and this field was present more that once in the MD, the
form-configurator.xml was not inserting the element selected by the field's
xpath, but its direct child. If the element was present only once in the MD,
the behavior was correct and the element selected by the xpath was inserted.
Because the che:CHE_CI_ResponsibleParty was inserted in the editor instead of
the gmd:contact, it was not possible to delete it (its parent is a xlink).
=> Fix multi contact deletion

common/src/main/java/org/fao/geonet/utils/XmlRequest.java, core/src/main/java/org/fao/geonet/notifier/MetadataNotifierClient.java, core/src/main/java/org/fao/geonet/util/GeocatXslUtil.java, geocat-services/src/main/java/org/fao/geonet/geocat/cgp/SOAPRequest.java, harvesters/src/main/java/org/fao/geonet/component/harvester/csw/Harvest.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/ogcwxs/Harvester.java, services/src/main/java/org/fao/geonet/services/metadata/format/Format.java
Now can follow redirects, switch to GET when HEAD is not supported and accept
only a 2xx status.
=> Improve URL checks

harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemHarvester.java, harvesters/src/main/java/org/fao/geonet/kernel/harvest/harvester/localfilesystem/LocalFilesystemParams.java, web-ui/src/main/resources/catalog/locales/du-admin.json, web-ui/src/main/resources/catalog/locales/en-admin.json, web-ui/src/main/resources/catalog/locales/es-admin.json, web-ui/src/main/resources/catalog/locales/fr-admin.json, web-ui/src/main/resources/catalog/locales/ge-admin.json, web-ui/src/main/resources/catalog/locales/it-admin.json, web-ui/src/main/resources/catalog/locales/ko-admin.json, web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.html, web-ui/src/main/resources/catalog/templates/admin/harvest/type/filesystem.js, web/src/main/webapp/loc/eng/xml/harvesting.xml, web/src/main/webapp/loc/fre/xml/harvesting.xml, web/src/main/webapp/loc/ger/xml/harvesting.xml, web/src/main/webapp/loc/ita/xml/harvesting.xml, web/src/main/webapp/xsl/harvesting/filesystem/filesystem.xsl, web/src/main/webapp/xsl/xml/harvesting/filesystem.xsl
Now, the user can configure a local harvester to run a script before the
files are harvested. For example, this can be used to do a rsync of a remote
directory.
=> Add beforeScript in the local harvester

domain/src/main/java/org/fao/geonet/domain/SchematronCriteria.java, web-ui/src/main/resources/catalog/components/admin/schematron/SchematronEditCriteriaDirective.js, web-ui/src/main/resources/catalog/components/admin/schematron/partials/criteria-viewer.html, web-ui/src/main/resources/catalog/js/admin/SchematronAdminController.js, web-ui/src/main/resources/catalog/style/gn_admin.less, web-ui/src/main/resources/catalog/templates/admin/metadata/schematron.html
See https://github.com/geonetwork/core-geonetwork/pull/1753 and https://jira.swisstopo.ch/browse/GEOCAT_SB-366?focusedCommentId=18861&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-18861 for the details.
This is a backport of the upstream PR, since both tree do not exactly match, some aspects of the previous PR could not be ported. The modification onto CheckUserName.java for instance, since the file does not exist in GeoCat. The rest of the modifications seemed coherent to me, even if I'm not a client-side expert on the modified parts.
Tests: untested yet, it would at least deserve a runtime one.
=> Backport 1753

core/src/main/java/org/fao/geonet/kernel/mef/Importer.java
Tests:
* testsuite is broken (and will need an update of the java libasm, because it is unable to parse Java Bytecode 52 format, but this would also require an update of springframework ...), no unit tests related to the mef import have been found though.
* Tests OK at runtime: importing a ZIP file containing 1 MD: the privileges publish & notify are correctly set after import.
Note:
Might deserve an upstream PR since the group is also ignored in 3.2.x:
https://github.com/geonetwork/core-geonetwork/blob/develop/core/src/main/java/org/fao/geonet/kernel/mef/Importer.java#L349-L379
=> MEF import - groupOwner is ignored (SB-531)

core/src/main/java/org/fao/geonet/geocat/kernel/AapMetadataReport.java, core/src/test/java/org/fao/geonet/geocat/kernel/AapMetadataReportTest.java, core/src/test/resources/org/fao/geonet/geocat/kernel/aap.xml, core/src/test/resources/org/fao/geonet/geocat/kernel/issue-export-SB451.xml, core/src/test/resources/org/fao/geonet/geocat/kernel/mdaaptest.xml, schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl, web/src/main/webapp/xsl/aap-report-csv.xsl
Following my previous work on AAP, some fields were missing the CSV export (see https://jira.swisstopo.ch/browse/GEOCAT_SB-451 for the details).
Tests: adapted related testsuite, tested the current branch onto tc-geocat.dev
=> AAP - some fixes related to CSV export (SB-451)

core/src/main/java/org/fao/geonet/geocat/kernel/AapMetadataReport.java, core/src/test/java/org/fao/geonet/geocat/kernel/AapMetadataReportTest.java, core/src/test/resources/org/fao/geonet/geocat/kernel/sb451-export-title-lang-mismatch.xml
In a xpath.selectNodes() call, you cannot predict the actual order of the list containing the selected elements. a selectSingleNode() will return the first object of the previous list, we want to make sure of
the selection order, and we end up doing it by hand, splitting the xpath.
Tests:
- updated testsuite for AAP (be careful that the behaviour is not exactly the same between junit and the live webapp). Even without the modification in AapMetadataReport, the newly added test was passing.
- runtime-tested
Note:
the same approach might be necessary for the other xpaths, but let's see.
=> sb-451 - forcing xpath selection order

schemas/iso19139/src/main/plugin/iso19139/formatter/groovy/iso19139/Handlers.groovy
This commit will escape `&` to `&amp;`
See https://github.com/geonetwork/core-geonetwork/commit/22a8117d48e946c4a4dddddc3032da8579f77149
=> Fix Loading of graphicoverview with '&'

schemas/iso19139.che/src/main/plugin/iso19139.che/extract-relations.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/process/onlinesrc-add.xsl, schemas/iso19139/src/main/plugin/iso19139/extract-relations.xsl, schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl, schemas/iso19139/src/main/plugin/iso19139/process/thumbnail-add.xsl, services/src/main/java/org/fao/geonet/api/records/model/related/ObjectFactory.java, services/src/main/java/org/fao/geonet/api/records/model/related/RelatedItem.java, services/src/main/java/org/fao/geonet/api/records/model/related/relatedResponse.xsd, web-ui/src/main/resources/catalog/components/edit/multilingualfield/MultilingualFieldDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcDirective.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/OnlineSrcService.js, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/addOnlinesrc.html, web-ui/src/main/resources/catalog/components/edit/onlinesrc/partials/onlinesrcList.html
Fix oneline resources in multilingual mode.
Add support of localized url in the UI.
- url can be multilingual or only one input
- OCGProtocol set to WMS if contains get-map
- add config in schema to tell if a field is multilingual or not
- hide name and description if adding multiple WMS
- manage url checker for both cases
- manage image display for both cases
- display proper url or name in onlinesrc list
=> Add multilingual support for URL in online resources

schemas/iso19139.che/src/main/plugin/iso19139.che/layout/config-editor.xml, schemas/iso19139/src/main/plugin/iso19139/layout/config-editor.xml
See [MGEO_SB-151](https://jira.swisstopo.ch/browse/MGEO_SB-151)
Freetext keywords are disabled by this PR in iso19139 schema.
=> Disable free text keywords in editor (MGEO_SB-151)

domain/src/main/java/org/fao/geonet/domain/SchematronCriteriaType.java, geocat/pom.xml, geocat/src/main/java/org/fao/geonet/geocat/services/aap/AapMetadataReport.java, geocat/src/test/java/org/fao/geonet/geocat/services/aap/AapMetadataReportTest.java, geocat/src/test/resources/org/fao/geonet/geocat/services/aap/aap.xml, geocat/src/test/resources/org/fao/geonet/geocat/services/aap/issue-export-SB451.xml, geocat/src/test/resources/org/fao/geonet/geocat/services/aap/mdaaptest-noaap.xml, geocat/src/test/resources/org/fao/geonet/geocat/services/aap/mdaaptest.xml, geocat/src/test/resources/org/fao/geonet/geocat/services/aap/sb451-export-title-lang-mismatch.xml, pom.xml, web-ui/src/main/resources/catalog/js/GnAdminMenu.js, web-ui/src/main/resources/catalog/js/admin/AdminController.js, web-ui/src/main/resources/catalog/templates/admin/geocat.html, web/pom.xml, web/src/main/webapp/WEB-INF/config-security/config-security-mapping.xml, web/src/main/webapp/WEB-INF/config.xml, web/src/main/webapp/xslt/geocat/aap-report-csv.xsl
Port AAP report to geocat 3.4.x.
Original work: https://github.com/geoadmin/geocat/pull/36
=> AAP report

Jenkinsfile, web/pom.xml
Rewriting the Jenkinsfile so that it can be compliant with the CI deployed by Camptocamp (https://ci.camptocamp.com).
There is currently an issue using the `withDockerContainer { sh "..." }` syntax in the Jenkinsfiles reguarding to the corporate CI: the slaves are randomly hanging on some shell commands, making the builds fail with unexpected return codes. This rewrite aims to emulate the previous failing syntax, leaving the management of the docker build container logic.
Tests: https://ci.camptocamp.com/job/geospatial/job/geocat/job/rewrite-jenkinsfile/20/ kindof passed, but the testsuite is broken anyway.
TODO: for now, the "-fn" maven option is used to avoid failing in case of broken tests. This should be replaced by a "-fae" (fail-at-end) once the testsuite is repaired. I used the …
=> Rewrite jenkinsfile

web/src/main/webapp/WEB-INF/classes/setup/sql-geocat/v340/migrate/migrate-default.sql
Values have been copied from the `prod` instance using `pg_dump` with `--data-only`.
Note: harvesters will have to be created&configured to use these groups.
=> Add groups used by harvesters in the SQL migration script

web/src/main/webapp/WEB-INF/data/data/formatter/html/text-el.html, web/src/main/webapp/WEB-INF/data/data/formatter/html/url-el.html, web/src/main/webapp/WEB-INF/data/data/formatter/html/wikitext-el.html
This compensates the fact that some labels are truncated by bootstrap:
=> Add title attributes in groovy formatter (MGEO_SB-244)

web-ui/src/main/resources/catalog/style/gn_metadata.less, web/src/main/webapp/WEB-INF/data/data/formatter/html/text-el.html, web/src/main/webapp/WEB-INF/data/data/formatter/html/url-el.html, web/src/main/webapp/WEB-INF/data/data/formatter/html/wikitext-el.html
Changes are made in `gn_metadata.less`:
* `dt` and `dd` are now all encapsulated in a `div.md-test` element, as it was before (I think)
* `padding` has been restored in `dd` elements
* word wrap has been restored in `dt` elements
* no width limit in tabs
After:
Before:
Note: this should be backported in GN afterwards
=> Improved the html formatter again

schemas/iso19139.che/src/main/plugin/iso19139.che/process/onlinesrc-add.xsl, schemas/iso19139/src/main/plugin/iso19139/process/onlinesrc-add.xsl
Without this commit the `updateKey` used to match an existing online resource would never match any element as the `gco:CharacterString` is always set even for localized strings.
Fixes: https://jira.swisstopo.ch/browse/MGEO_SB-343
=> Fix updating existing online resources (MGEO_SB-343)

s3sync-geocat-folders.sh
extract from aws s3 sync help:
--delete  (boolean)  Files that exist in the destination but not in the
source are deleted during sync.
=> add --delete to s3 sync command fix #MGEO_SB-372

schemas/iso19139.che/src/main/plugin/iso19139.che/process/keywords-mapper.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/process/massive-content-update-clean-changes.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/process/massive-content-update-extract-changes.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/process/massive-content-update.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/process/url-host-relocator.xsl
The following processes were non functional in iso.che:
* URL replacer
* Keyword mapper
* Batch replacer
I've adapted the first and last ones for the CHE profile. The keyword mapper would need to be rewritten entirely since all keywords are now handled through xlinks. I simply took the most recent code from the iso19139 schema for now.
=> Adapt batch processes for iso19139.che

schemas/iso19139.che/src/main/plugin/iso19139.che/formatter/groovy/iso19139che/Handlers.groovy, web-ui/src/main/resources/catalog/components/catalog/CatalogService.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html
Either in angular JS view or groovy formatter, compare the bounding box bounds with the [EPSG:21781 range](http://spatialreference.org/ref/epsg/21781/).
If bounds exceed this range, switch to EPSG:4326 with an OSM background (the swisstopo basemap cannot be used anymore).
Example with record `248211e2-fd0a-40ee-94d8-3ab80e934250`:
=> Handle extents outside of the EPSG:21781 range

core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java
From historical reason ?, update-fixed-info (ufo) was not applied to templates. But now, this is causing issue as ufo is making important changes which also applies to template. eg. all thesaurus handling, nilReason, codelist updates, gml@id, ... When editors try to validate template they are facing issues that they don't have with records. So it does not make much sense to not apply ufo to template.
I would wait approval on GN side before merging in order to get feedback first.
=> Editing / Update-fixed-info applies to template

schemas/iso19139.che/src/main/plugin/iso19139.che/update-fixed-info.xsl
Removing mime type element substitution (not used in geocat.ch). This will fixed the associated panel name editing which currently is always removed.
Related to https://github.com/geonetwork/core-geonetwork/pull/3983
=> MGEO_SB-474 / ISO19139.che / Computing mime type is not taking into account multilingual element

schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/default.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl
Translate the codelist with the correct language code even in
not multilingual record (and fix it for multilingual).
Make the contact field contact the same in all indices (with position
and uuid) to avoid to have distinct value in angular view.
=> Angular view / Fix duplicate contact (MGEO_SB-470)

schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/default.xsl, schemas/iso19139.che/src/main/plugin/iso19139.che/index-fields/language-default.xsl
Mainly needed for harvested records which may not respect the rule.
It will also fix facet counter for parent category.
See https://jira.swisstopo.ch/browse/MGEO_SB-483
=> Indexing / Topic category / Index parent too if not defined

web/src/main/webapp/xslt/geocat/xml_iso19139.xsl
https://jira.swisstopo.ch/browse/MGEO_SB-606
Use `gmd:URL` if available in linkages when converting from CHE to 19139.
=> MGEO_SB-606 / use gmd:URL if available in CHE>iso19139 transformation

schemas/iso19139.che/src/main/java/org/fao/geonet/schema/iso19139che/ISO19139cheSchemaPlugin.java
Related to https://jira.swisstopo.ch/browse/MGEO_SB-490
`gmx:Anchor` should be handled like `gco:CharacterString`
=> ISO19139.che / Fix usage of PT_FreeUrl for Anchor element

web-ui/src/main/resources/catalog/components/search/formfields/FormFieldsDirective.js, web-ui/src/main/resources/catalog/js/edit/NewMetadataController.js, web-ui/src/main/resources/catalog/templates/editor/import.html
* Import / Group contains blank value only if admin
* Avoid duplicated empty option in list (add optional first and select first item)
* New metadata / Don't select first user group in the list - let the group combo directive take care of the default based on config.
https://jira.swisstopo.ch/browse/MGEO_SB-580
=> Import & new metadata / Consistent group list.

core/src/main/java/org/fao/geonet/kernel/AllThesaurus.java, core/src/main/java/org/fao/geonet/kernel/ThesaurusManager.java, core/src/main/java/org/fao/geonet/kernel/search/keyword/KeywordSearchParams.java, core/src/main/resources/config-spring-geonetwork-parent.xml, core/src/test/java/org/fao/geonet/kernel/AllThesaurusTest.java, core/src/test/java/org/fao/geonet/kernel/search/KeywordsSearcherTest.java
>
> In some setup, a thesaurus is used to populate a field which is not a keyword. In that case, the catalogue should not list those thesaurus element for general keywords so that the thesaurus is only used to populate the specific field.
=> Thesaurus / All / Add the possibility to exclude.
